#!/bin/bash
clear
source ./progress_bar.sh
printf -- '\033[33m Acquiring prerequisites package needed for install \033[0m\n';
setup_scroll_area
printf -- '\033[33m[?] -->  flex             \033[0m\n';
sleep 0.2        
printf -- '\033[33m[?] -->  bison            \033[0m\n';
sleep 0.2        
printf -- '\033[33m[?] -->  libpcap-dev      \033[0m\n';
sleep 0.2        
printf -- '\033[33m[?] -->  libtool-bin      \033[0m\n';
sleep 0.2        
printf -- '\033[33m[?] -->  automake         \033[0m\n';
sleep 0.2        
printf -- '\033[33m[?] -->  libpcre++-dev    \033[0m\n';
sleep 0.2        
printf -- '\033[33m[?] -->  libdeubnet-dev   \033[0m\n';
sleep 0.2        
printf -- '\033[33m[?] -->  libdnet          \033[0m\n';
sleep 0.2        
printf -- '\033[33m[?] -->  libluajit-5.1-dev\033[0m\n';
sleep 0.2        
printf -- '\033[33m[?] -->  libnighttp2-dev  \033[0m\n';
sleep 0.2        
printf -- '\033[33m[?] -->  libssl-dev       \033[0m\n';
sleep 0.2        
printf -- '\033[33m[?] -->  pkgconfig        \033[0m\n';
sleep 0.2        
sudo apt update
sleep 0.2
printf -- '\033[33m Checking/Installing FLEX \033[0m\n';
sudo apt-get install -y flex 
draw_progress_bar 1
sleep 0.2
printf -- '\033[33m Checking/Installing BISON \033[0m\n';
sudo apt-get install -y bison 
draw_progress_bar 2
sleep 0.2
sudo apt-get install -y libpcap-dev 
draw_progress_bar 3
sleep 0.2
sudo apt-get install -y libtool-bin
draw_progress_bar 4
sleep 0.2
sudo apt-get install -y automake
draw_progress_bar 5
sleep 0.2
sudo apt-get install -y libpcre++-dev 
draw_progress_bar 6
sleep 0.2
sudo apt-get install -y libdumbnet-dev
draw_progress_bar 7
sleep 0.2
sudo apt-get install -y libdnet
draw_progress_bar 8
sleep 0.2
sudo apt-get install -y libluajit-5.1-dev 
draw_progress_bar 9
sleep 0.2
sudo apt-get install -y libnghttp2-dev 
draw_progress_bar 10
sleep 0.2
sudo apt-get install -y libssl-dev 
draw_progress_bar 11
sleep 0.2
sudo apt-get install -y pkg-config
draw_progress_bar 11
sleep 0.2
clear
printf -- '\033[32m All prerequisites package are installed  \033[0m\n';
sleep 0.5
printf -- '\033[33m[OK] -->  flex             \033[0m\n';
sleep 0.2        
printf -- '\033[33m[OK] -->  bison            \033[0m\n';
sleep 0.2        
printf -- '\033[33m[OK] -->  libpcap-dev      \033[0m\n';
sleep 0.2        
printf -- '\033[33m[OK] -->  libtool-bin      \033[0m\n';
sleep 0.2        
printf -- '\033[33m[OK] -->  automake         \033[0m\n';
sleep 0.2        
printf -- '\033[33m[OK] -->  libpcre++-dev    \033[0m\n';
sleep 0.2        
printf -- '\033[33m[OK] -->  libdeubnet-dev   \033[0m\n';
sleep 0.2        
printf -- '\033[33m[OK] -->  libdnet          \033[0m\n';
sleep 0.2        
printf -- '\033[33m[OK] -->  libluajit-5.1-dev\033[0m\n';
sleep 0.2        
printf -- '\033[33m[OK] -->  libnighttp2-dev  \033[0m\n';
sleep 0.2        
printf -- '\033[33m[OK] -->  libssl-dev       \033[0m\n';
sleep 0.2        
printf -- '\033[33m[OK] -->  pkgconfig        \033[0m\n';
sleep 0.2        
draw_progress_bar 12
sleep 1
printf -- '\033[33m INSTALLING DAQ 2.0.6 \033[0m\n';
sleep 1
sudo wget https://snort.org/downloads/snort/daq-2.0.7.tar.gz
draw_progress_bar 13
sleep 0.2
sudo tar xvfz daq-2.0.7.tar.gz
draw_progress_bar 14
sleep 0.2
cd daq-2.0.7/
sudo ./configure
draw_progress_bar 15
sleep 0.2
sudo autoreconf -f -i
sleep 0.2
sudo make
draw_progress_bar 16
sleep 0.2
sudo make install
draw_progress_bar 25
sleep 0.2
printf -- '\033[32m DAQ 2.0.7 INSTALLED \033[0m\n';
sleep2
clear 
printf -- '\033[33m INSTALLING SNORT  \033[0m\n';
cd ..
sudo wget https://www.snort.org/downloads/snort/snort-2.9.17.tar.gz
draw_progress_bar 27
sleep 0.2
sudo tar -xvzf snort-2.9.17.tar.gz
draw_progress_bar 29
sleep 0.2
cd snort-2.9.16.1
draw_progress_bar 30
sleep 0.2
sudo ./configure --enable-sourcefire 
draw_progress_bar 35
sleep 0.2
sudo make 
draw_progress_bar 40
sleep 0.2
sudo make install
draw_progress_bar 50
sleep 0.2
clear
printf -- '\033[32m SNORT  INSTALLED \033[0m\n';
draw_progress_bar 50
sleep 0.2
clear
printf -- '\033[33m SETUP SNORT  \033[0m\n';
sudo ldconfig
sudo ln -s /usr/local/bin/snort /usr/sbin/snort
printf -- '\033[33m CREATING SNORT USER \033[0m\n';
sudo groupadd snort
sudo useradd snort -r -s /sbin/nologin -c SNORT_IDS -g snort
draw_progress_bar 60
sleep 0.5
clear
sudo mkdir -p /etc/snort/rules
sudo mkdir /var/log/snort
sudo mkdir /usr/local/lib/snort_dynamicrules
sudo chmod -R 5775 /etc/snort
sudo chmod -R 5775 /var/log/snort
sudo chmod -R 5775 /usr/local/lib/snort_dynamicrules
sudo chown -R snort:snort /etc/snort
sudo chown -R snort:snort /var/log/snort
sudo chown -R snort:snort /usr/local/lib/snort_dynamicrules
cd ..
cd snort-2.9.16.1/etc/
sudo cp *.conf /etc/snort
sudo cp *.config /etc/snort
sudo cp *.map /etc/snort
cd ..
cd ..
sudo cp /etc/snort/snort.conf /etc/snort/snort.2.9.17.original
sudo cp snort.original /etc/snort/snort.conf
draw_progress_bar 85
cd legendary
sudo cp -R * /etc/snort/
draw_progress_bar 95
sudo touch /etc/snort/rules/white_list.rules
sudo touch /etc/snort/rules/black_list.rules
sudo touch /etc/snort/rules/local.rules
printf -- '\033[33m SNORT CONFIGURATION DONE \033[0m\n';
sleep 0.5
clear
sudo snort -T -c /etc/snort/snort.conf
sleep  2
snort --version
exit






